# my global config
global:
  scrape_interval:     15s
  evaluation_interval: 30s
  
rule_files: []

scrape_configs:
- job_name: prometheus

  honor_labels: true
  
  static_configs:
  - targets: ['localhost:9090']
